### ISSUE TITLE
Dashboard reset

### ISSUE THREAD

**Issue by jgale011** [chrissbarnett/banana#2]
When the main settings window (top right button) is opened, it (a) renders incorrectly with all tabbed content appearing at once and (b) resets the contents of the dashboard. This leads to no new rows that can be added from this dialogue, or changing the solr instance once it has been set without recreating all widget information.

**Comment by chrissbarnett** [comment]
@jgale011 is this in a specific browser/machine?

**Comment by chrissbarnett** [comment]
dashboard reset fixed with cfb6d57ff541549e0d4ff0b6bf9fe61a2627a858
